#!/bin/bash

while getopts ":p:o:n:u:i:" opt; do
  case $opt in
    p) port="$OPTARG"
    ;;
    o) origin="$OPTARG"
    ;;
    n) name="$OPTARG"
    ;;
    u) username="$OPTARG"
    ;;
    i) keyfile="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

# Deploy DNS server
ssh -i $keyfile $username@<your_dns_server_ip> "mkdir -p ~/cs5700cdn"
scp -i $keyfile ./dnsserver $username@<your_dns_server_ip>:~/cs5700cdn/

# Deploy HTTP server
ssh -i $keyfile $username@<your_http_server_ip> "mkdir -p ~/cs5700cdn"
scp -i $keyfile ./httpserver $username@<your_http_server_ip>:~/cs5700cdn/
