#!/bin/bash

# Usage: ./deployCDN.sh -p <port> -o <origin> -n <name> -u <username> -i <keyfile>
dns_server="cdn-dns.5700.network"
http_server="cdn-http4.5700.network"
dnsserver_file="dnsserver"
httpserver_file="httpserver"

while getopts ":p:o:n:u:i:" opt; do
  case $opt in
    p) port="$OPTARG"
    ;;
    o) origin="$OPTARG"
    ;;
    n) name="$OPTARG"
    ;;
    u) username="$OPTARG"
    ;;
    i) keyfile="$OPTARG"
    ;;
  esac
done

# Deploy the DNS and HTTP server code to the respective servers
scp -i "$keyfile" dnsserver "${username}@cdn-dns.5700.network:"
scp -i "$keyfile" httpserver "${username}@cdn-http4.5700.network:"


