#!/usr/bin/env python3

import argparse
import socket
import requests

CACHE = {}

def handle_request(request, origin):
    path = request.split()[1]
    if path == "/grading/beacon":
        return b"HTTP/1.1 204 No Content\r\n\r\n"
    elif path in CACHE:
        return CACHE[path]
    else:
        url = 'http://' + origin + path
        response = requests.get(url)
        CACHE[path] = response.content
        return CACHE[path]

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--port', required=True, help="Port number to bind the HTTP server")
    parser.add_argument('-o', '--origin', required=True, help="Origin server for the CDN")
    args = parser.parse_args()

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(("", int(args.port)))
    sock.listen()

    while True:
        conn, addr = sock.accept()
        data = conn.recv(1024)
        response = handle_request(data.decode(), args.origin)
        conn.sendall(response)
        conn.close()

if __name__ == "__main__":
    main()
