#!/bin/bash

# Usage: ./runCDN.sh -p <port> -o <origin> -n <name> -u <username> -i <keyfile>

while getopts ":p:o:n:u:i:" opt; do
  case $opt in
    p) port="$OPTARG"
    ;;
    o) origin="$OPTARG"
    ;;
    n) name="$OPTARG"
    ;;
    u) username="$OPTARG"
    ;;
    i) keyfile="$OPTARG"
    ;;
  esac
done

# Start the DNS and HTTP server remotely
ssh -i "$keyfile" "${username}@cdn-dns.5700.network" "./dnsserver -p $port -n $name" &
ssh -i "$keyfile" "${username}@cdn-http4.5700.network" "./httpserver -p $port -o $origin" &


