#!/bin/bash

while getopts ":p:o:n:u:i:" opt; do
  case $opt in
    p) port="$OPTARG"
    ;;
    o) origin="$OPTARG"
    ;;
    n) name="$OPTARG"
    ;;
    u) username="$OPTARG"
    ;;
    i) keyfile="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

# Start DNS server
ssh -i $keyfile $username@<your_dns_server_ip> "cd ~/cs5700cdn && nohup ./dnsserver -p $port -n $name > /dev/null 2>&1 &"

# Start HTTP server
ssh -i $keyfile $username@<your_http_server_ip> "cd ~/cs5700cdn && nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &"
