#!/bin/bash

while getopts ":u:i:" opt; do
  case $opt in
    u) username="$OPTARG"
    ;;
    i) keyfile="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

# Stop DNS server
ssh -i $keyfile $username@<your_dns_server_ip> "pkill -f dnsserver"

# Stop HTTP server
ssh -i $keyfile $username@<your_http_server_ip> "pkill -f httpserver"
