#!/bin/bash

while getopts ":u:i:" opt; do
  case $opt in
    u) username="$OPTARG"
    ;;
    i) keyfile="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

# Stop DNS server
ssh -i $keyfile $username@cdn-dns.5700.network "pkill -f dnsserver"

# Stop HTTP server
ssh -i $keyfile $username@cdn-http4.5700.network "pkill -f httpserver"
